### PR TITLE
ISSUE-1

### LINKED ISSUE #1: Basic Operations
All non-admin features should be supported.  Query builders should also not be included (and may always be out of scope).

### PR DESCRIPTION
**Pull request by binaryalchemist**
Support for basic operations, but no support for query builders for views or N1QL.  This PR closes #1.

### CODE REVIEW

**Comment by johndietz** [comment]
@binaryalchemist - consider adding:

```
"repository": {
    "type": "git",
    "url": "https://github.com/binaryalchemist/chesterfield.git"
  },
```

to your package.json

**Comment by binaryalchemist** [comment]
@johndietz, I updated the readme and added some things to the package.json.

**Comment by binaryalchemist** [comment]
I found a bug in one of the test ... I will let you know when I have a fix.

**Comment by binaryalchemist** [comment]
@johndietz these changes are now ready to go as far as I am concerned.

**Pull request merged**
